# Generated by Django 3.1.7 on 2021-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210527_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100, unique=True, verbose_name='项目名')),
                ('pro_intro', models.CharField(max_length=500, verbose_name='项目描述')),
            ],
        ),
    ]
